CRUD Article
Eli250/my-brand-api pull request #1
Opened 2022-01-27 16:48 UTC by Eli250

###What does this PR do?

CRUD Operations

###Description of Task to be completed?

To Create, read, update and delete article

###Relevant pivotal tracker stories?

Acn8iWWI

2022-01-28 13:02 UTC, ncutixavier requested changes

2022-01-28 17:51 UTC, Eli250 commented on src/controllers/articleController.js
> +      res.send({ error: "There was an error creating article!" });
I have applied the comments you sent me.

2022-01-31 13:36 UTC, ncutixavier approved these changes

2022-01-31 14:07 UTC, ncutixavier approved these changes
Change your PR title to follow naming convention

2022-01-31 16:56 UTC, merged